services:
  server:
    restart: unless-stopped
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}

  client:
    restart: unless-stopped

  nginx:
    restart: unless-stopped
    ports:
      - "80:80"

  postgres:
    restart: unless-stopped
